#!/bin/bash

if [[ $1 != "" ]] && [[ $2 != "" ]]; then
  INPUT=$1
  OUTPUT=$2
  ffmpeg -hide_banner -v warning -i $INPUT -filter_complex "[0:v] scale=320:-1:flags=lanczos,split [a][b]; [a] palettegen=reserve_transparent=on:transparency_color=ffffff [p]; [b][p] paletteuse" $OUTPUT
else
  echo -e "\ngif_resizer:"
  echo -e "Example usage: "
  echo -e "     gif_resizer INPUT_FILE.gif OUTPUT_FILE.gif\n"
  echo -e "     Will resize your gif to 320 height or width, whichever looks better\n"
fi

